# -*- coding: utf-8 -*-
"""Assg1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YbKOZEmSsjGytmzPPboZwcD9R5-DQPFS
"""

s1="thisismyfirstpythonprogramming256classandiamlearningpythonstringanditsfunction"
print(s1[1:300:3])
print(s1[::1])
print(s1.upper())
print(s1.lower())
print(s1.capitalize())
print(s1.isalnum())
s3="v\tasantha"
print(s3.expandtabs(1))
print(s3.expandtabs(4))
s4="  vasantha "
print(s4.strip())
print(s4.lstrip())
print(s4.rstrip())
print(s4.replace ("vasantha","vassu"))
s="vinu"
print(s.center(10,"6"))

s2='sdfga276'

s2.isalpha()
s2.isalnum()